#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/LKM_prod
#    username: lkm_prod_user
#    password: guru
#  jpa:
#    hibernate:
#     ddl-auto: validate
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    database: mysql
#    show-sql: false





spring:

  spring.jpa.show-sql: false

  datasource:
#    url: jdbc:mysql://localhost:3306/LKM_dev
#    username: lkm_dev_user
#    password: guru

    url: jdbc:mysql://sql.freedb.tech:3306/freedb_LK_Manager
    username: freedb_kingsajz
    password: nA6&AamUW?jywrm




  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #  database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: false
    logging.level.org.hibernate.SQL : DEBUG
    logging.level.org.springframework.web: DEBUG
    #org:
    # hibernate:
    #  dialect:
    #   MySQLDialect:
