


spring:

  spring.jpa.show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/LKM_dev
    username: lkm_dev_user
    password: guru






  jpa:
    hibernate:

      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  #  database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: true

    logging.level.org.hibernate.SQL : DEBUG
    logging.level.org.springframework.web: DEBUG
#org:
 # hibernate:
  #  dialect:
   #   MySQLDialect:
